  
  // import photo for object
  import news3Photo from '../main/photo/photo_1734.png'
  import news2Photo from '../main/photo/photo_1732.png'
  import news1Photo from '../main/photo/photo_1721.png'
  
  //news objects 
const news = [
    {
      id: 1,
      title: 'Energy-saving technologies on the rise',
      image: news1Photo,
      text: 'In recent years, energy-saving technologies have become increasingly popular, and many companies are now investing in these solutions to reduce their environmental impact and save money on their energy bills. One such company is ABC Energy, which has just announced the launch of its new energy-saving technology, SmartSaver.SmartSaver uses a combination of machine learning algorithms and real-time energy consumption data to optimize energy usage and reduce waste. The technology can be installed in commercial buildings and factories, and can lead to energy savings of up to 30%."SmartSaver is a game-changer in the energy industry," said John Doe, CEO of ABC Energy. "We are excited to offer this innovative solution to our clients and help them achieve their energy efficiency goals." ABC Energy has announced the launch of their new energy-saving technology that promises to cut energy usage by up to 50%. The new system, known as EnergySave, uses a combination of cutting-edge sensors and AI technology to analyze energy usage in real-time and make adjustments accordingly. This means that businesses and homeowners alike can reduce their carbon footprint and save money on their energy bills at the same time. EnergySave is set to be a game-changer in the industry, and ABC Energy is proud to be leading the charge towards a more sustainable future.'
    },
    {
      id: 2,
      title: 'Wind power plant generates record energy output',
      image: news2Photo,
      text: 'DEF Energy has announced the construction of three new wind power plants that will supply electricity to over 50,000 homes in the local area. The plants, which will be built over the next two years, will be equipped with state-of-the-art turbines that can generate up to 3 megawatts of electricity each. This is part of DEF Energys commitment to providing clean, renewable energy to their customers and reducing their reliance on fossil fuels. The company hopes that this project will inspire others to follow suit and invest in clean energy technologies.XYZ Energy, one of the worlds leading renewable energy companies, has announced that its wind power plant in the North Sea has set a new record for energy output. The plant, which has been in operation for three years, generated 15.6 terawatt-hours of energy in 2022, exceeding its previous record of 14.3 terawatt-hours set in 2021.The wind power plant, which features advanced wind turbines with a capacity of 12 megawatts each, has become a key contributor to the UK is renewable energy mix, supplying clean energy to over 3 million households in the region."We are proud of the achievement of our North Sea wind power plant," said Jane Smith, CEO of XYZ Energy."It shows the power of renewable energy and its potential to drive the transition towards a more sustainable future."'
    },
    {
      id: 3,
      title: 'New technology to revolutionize solar energy',
      image: news3Photo,
      text: 'A team of scientists at DEF Energy has developed a new technology that could revolutionize the way solar energy is generated and stored. The technology, called SunStor, is a hybrid solar panel that combines photovoltaic cells with a thermal energy storage system.The photovoltaic cells convert sunlight into electricity, while the thermal energy storage system captures the heat generated by the cells and stores it for later use. This enables the system to generate both electricity and heat, making it more efficient and cost-effective than traditional solar panels."SunStor has the potential to transform the solar energy industry,said Dr. David Lee, lead scientist at DEF Energy, - "It is  a game-changer for residential and commercial customers who want to generate their own clean energy and reduce their reliance on the grid."GHI Energy has announced the development of a groundbreaking new solar panel technology that has the potential to revolutionize the industry. The new panels, known as SunBoost, use a series of mirrors and lenses to focus sunlight onto a small area of photovoltaic cells, increasing their efficiency by up to 60%. This means that SunBoost panels can generate more electricity than traditional solar panels, making them a more cost-effective option for homeowners and businesses alike. GHI Energy is confident that this new technology will help to accelerate the transition towards renewable energy and reduce our dependence on fossil fuels.'
    },
  ];
  
  export default news